### ISSUE TITLE
Palindrome by python

### ISSUE THREAD

**Issue by amangoyal0285** [divyanshagarwal053/html#3]
# function to check string is palindrome or not

def isPalindrome(s):
 

    # Using predefined function to

    # reverse to string print(s)

    rev = ''.join(reversed(s))
 

    # Checking if both string are

    # equal or not

    if (s == rev):

        return True

    return False
 
# main function

s = "malayalam"

ans = isPalindrome(s)
 

if (ans):

    print("Yes")

else:

    print("No")

**Comment by amritagarwal02** [comment]
Please assign me

**Comment by amangoyal0285** [comment]
Can i
